name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main

# Add this permissions block
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Updated to v4 for best practice
      - uses: actions/setup-node@v4 # Updated to v4 for best practice
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist